### ISSUE TITLE
datasource.s3.endpoint must be a `string` type, but the final value was: `null`

### ISSUE THREAD

**Issue by alois-gaucher** [dicedtomatoreal/typex#161]
Hello,

I just tried to run a Docker instance of Zipline, and I have this error every time I start the container. I'm not using s3, only local.

This is my docker-compose:

```
zipline:
    container_name: zipline
    image: ghcr.io/diced/zipline/zipline:trunk
    networks:
      - web
      - database
    restart: always
    environment:
      - SECURE=false
      - SECRET='MYSUPERSECRET'
      - HOST=0.0.0.0
      - PORT=3000
      - DATASOURCE_TYPE=local
      - DATASOURCE_DIRECTORY=/zipline/uploads
      - DATABASE_URL=postgresql://postgres:**masked my local password**@postgres/zipline
      - UPLOADER_ROUTE=/u
      - UPLOADER_EMBED_ROUTE=/a
      - UPLOADER_LENGTH=6
      - UPLOADER_ADMIN_LIMIT=5000000000
      - UPLOADER_USER_LIMIT=104900000
      - UPLOADER_DISABLED_EXTS=
      - URLS_ROUTE=/go
      - URLS_LENGTH=6
    volumes:
      - '/home/docker/zipline/uploads:/zipline/uploads'
      - '/home/docker/zipline/public:/zipline/public'
```

The full error:

  |   | 2022-07-11 10:08:53 | stderr | }
-- | -- | -- | -- | --
  |   | 2022-07-11 10:08:53 | stderr | code: 'ERR_UNHANDLED_REJECTION'
  |   | 2022-07-11 10:08:53 | stderr | If "null" is intended as an empty value be sure to mark the schema as `.nullable()`".] {
  |   | 2022-07-11 10:08:53 | stderr | datasource.s3.endpoint must be a `string` type, but the final value was: `null`.
  |   | 2022-07-11 10:08:53 | stderr | [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1 errors occured
  |   | 2022-07-11 10:08:53 | stderr | ^
  |   | 2022-07-11 10:08:53 | stderr | triggerUncaughtException(err, true /* fromPromise */);
  |   | 2022-07-11 10:08:53 | stderr | node:internal/process/promises:279
  |   | 2022-07-11 10:08:53 | stdout | 2022-07-11 08:08:53,529 AM INFO  [config] reading environment
  |   | 2022-07-11 10:08:53 | stdout | 2022-07-11 08:08:53,463 AM INFO  [server] starting zipline@3.4.8 server
  |   | 2022-07-11 10:08:49 | stderr | }

Thanks for your help
