### ISSUE TITLE
Environment Variables are not respected

### ISSUE THREAD

**Issue by MrMysterius** [dicedtomatoreal/typex#177]
Some or all of my environment variables are not respected or used.

The `CORE_HTTPS` is not getting used or always defaults to `false`, because I always get back URLs only with `http` not `https`.
As well are the `DISCORD_XX` variables don't seem to work since I'm not getting any messages/events send through the webhook.

The Zipline Part of my `docker-compose.yml` is this:

```yaml
zipline:
  image: ghcr.io/diced/zipline
  ports:
    - '10.10.10.100:9200:3000'
  restart: always
  environment:
    CORE_HTTPS: true
    CORE_SECRET: REDACTED
    CORE_HOST: 0.0.0.0
    CORE_PORT: 3000
    CORE_DATABASE_URL: REDACTED
    CORE_LOGGER: true
    UPLOADER_ROUTE: /f
    URLS_LENGTH: 6
    URLS_ROUTE: /s
    DISCORD_URL: "REDACTED"
    DISCORD_UPLOAD: "[:page_facing_up: {file.created_at.full_string}] {user.name} - {link}"
    DISCORD_SHORTEN: "[:link: {url.created_at.full_string}] {user.name} - {link}"
  volumes:
    - './uploads:/zipline/uploads'
    - './public:/zipline/public'
  depends_on:
    - 'postgres'
```
