### ISSUE TITLE
Bug: Docker - migration error

### ISSUE THREAD

**Issue by alois-gaucher** [dicedtomatoreal/typex#271]
### What happened?

Since the latest update of the trunk image, my Zipline container can't start. It seems like it's a database-migration error.

Here is my docker-compose

```
zipline:
    container_name: zipline
    image: ghcr.io/diced/zipline:trunk
    networks:
      - web
      - database
    restart: always
    environment:
      - CORE_HTTPS=false
      - 'CORE_SECRET=******************'
      - CORE_HOST=0.0.0.0
      - CORE_PORT=3000
      - CORE_DATABASE_URL=postgresql://postgres:***************@postgres/zipline
      - CORE_LOGGER=true
      - DATASOURCE_TYPE=local
      - DATASOURCE_DIRECTORY=./uploads
      - UPLOADER_ROUTE=/u
      - UPLOADER_EMBED_ROUTE=/a
      - UPLOADER_LENGTH=6
      - UPLOADER_ADMIN_LIMIT=5245000000
      - UPLOADER_USER_LIMIT=1049000000
      - UPLOADER_DISABLED_EXTS=
      - URLS_ROUTE=/go
      - URLS_LENGTH=6
    volumes:
      - '/home/*****/docker/useful-apps/zipline/uploads:/zipline/uploads'
      - '/home/*****/docker/useful-apps/zipline/public:/zipline/public'
```

Please let me know if you need any additional information !

### Version

upstream (ghcr.io/diced/zipline:trunk)

### Zipline Logs

```shell
Node.js v19.4.0 |  
-- | --
  |   | } |  
  |   | batchRequestIdx: undefined |  
  |   | meta: { column: 'Invite.expiresAt' }, |  
  |   | clientVersion: '4.8.1', |  
  |   | code: 'P2022', |  
  |   | at start (/zipline/src/server/index.ts:107:12) { |  
  |   | at Object.clearInvites (/zipline/src/server/index.ts:122:7) |  
  |   | at async PrismaClient._request (/zipline/node_modules/@prisma/client/runtime/index.js:36082:16) |  
  |   | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) |  
  |   | at RequestHandler.request (/zipline/node_modules/@prisma/client/runtime/index.js:34991:12) |  
  |   | at RequestHandler.handleAndLogRequestError (/zipline/node_modules/@prisma/client/runtime/index.js:34996:12) |  
  |   | at RequestHandler.handleRequestError (/zipline/node_modules/@prisma/client/runtime/index.js:35024:13) |  
  |   | The column `Invite.expiresAt` does not exist in the current database. |  
  |   | Invalid `prisma.invite.deleteMany()` invocation: |  
  |   | PrismaClientKnownRequestError: |  
  |   | ^ |  
  |   | throw new PrismaClientKnownRequestError(message, { |  
  |   | /zipline/node_modules/@prisma/client/runtime/index.js:35024 |  
  |   | 2023-01-16 10:30:56,178 AM info  [server] started production zipline@3.7.0-rc1 server |  
  |   | 2023-01-16 10:30:56,178 AM info  [server] listening on 0.0.0.0:3000 |  
  |   | 2023-01-16 10:30:55,176 AM info  [datasource] using Local(./uploads) datasource


```
```


### Browser Logs

_No response_

### Additional Info

_No response_
