### ISSUE TITLE
Bug: docker-compose not working

### ISSUE THREAD

**Issue by changchichung** [dicedtomatoreal/typex#400]
### What happened?

PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-05-09 01:51:46.869 UTC [1] FATAL:  database files are incompatible with server
2023-05-09 01:51:46.869 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 14, which is not compatible with this version 15.2 (Debian 15.2-1.pgdg110+1).

### Version

upstream (ghcr.io/diced/zipline:trunk)

### Zipline Logs

```shell
2023-05-09 01:52:19,226 AM info  [datasource] using Local(./uploads) datasource
2023-05-09 01:52:19,254 AM info  [database::migrations] establishing database connection
2023-05-09 01:52:19,254 AM info  [database::migrations] ensuring database exists, if not creating database - may error if no permissions
2023-05-09 01:52:24,308 AM error [database::migrations] Unable to connect to database `postgres://postgres:postgres@postgres/postgres`, check your database connection
```

### Additional Info

docker-compose.yml
```
version: '3'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  zipline:
    image: ghcr.io/diced/zipline
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      - CORE_RETURN_HTTPS=false
      - CORE_SECRET=somesupersecrettext
      - CORE_HOST=0.0.0.0
      - CORE_PORT=3000
      - CORE_DATABASE_URL=postgres://postgres:postgres@postgres/postgres
      - CORE_LOGGER=true
    volumes:
      - './uploads:/zipline/uploads'
      - '$PWD/public:/zipline/public'
    depends_on:
      - 'postgres'

volumes:
  pg_data:

```
