### ISSUE TITLE
Bug: All pages stuck on loading

### ISSUE THREAD

**Issue by wdhdev** [dicedtomatoreal/typex#514]
### What happened?

All pages are stuck on loading, however uploading via ShareX still works.

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Chrome 120.0.6099.109 (Official Build) (64-bit)

### Zipline Logs

```shell
There are no error logs, everything is returning status 200, even when enabling DEBUG mode.
```

### Browser Logs

```shell
No browser logs.
```

### Additional Info

![NaIxtwxp](https://github.com/diced/zipline/assets/87287585/e418db6f-96d2-4b5d-8269-08c38e4748c4)
![qAnJpanX](https://github.com/diced/zipline/assets/87287585/3ae37c9f-c29a-4afe-bf3a-134238ed0248)
![uWRteo6C](https://github.com/diced/zipline/assets/87287585/13696d9a-06ee-42a6-888e-e4b4476e619a)
![XDKdl7ni](https://github.com/diced/zipline/assets/87287585/1b825f33-5a68-46ed-877d-b751aa3002bc)

I'm running Zipline using Portainer Stacks, this is my Docker compose file:
```yaml
version: '3'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  zipline:
    image: ghcr.io/diced/zipline
    ports:
      - '4000:3000'
    restart: unless-stopped
    hostname: zipline
    environment:
      - CORE_RETURN_HTTPS=true
      - CORE_SECRET=CENSORED
      - CORE_HOST=0.0.0.0
      - CORE_PORT=3000
      - CORE_DATABASE_URL=postgres://postgres:postgres@postgres/postgres
      - CORE_LOGGER=true
      - MFA_TOTP_ENABLED=true
      - UPLOADER_ADMIN_LIMIT=2gb
      - UPLOADER_USER_LIMIT=100mb
      - UPLOADER_ROUTE=/
      - UPLOADER_LENGTH=8
      - URLS_LENGTH=8
      - DEBUG=true
    volumes:
      - '/docker/zipline/uploads:/zipline/uploads'
      - '/docker/zipline/public:/zipline/public'
    depends_on:
      - 'postgres'

volumes:
  pg_data:
```

Docker Images:
`ghcr.io/diced/zipline:latest`: `sha256:f4946bd6c62c9e4b2a74a98c8d20b9ca607cf695e7a45f83e5eac7c0d0ecd731`
`postgres:15`: `sha256:4229ecebf88d0903fab70b2bf97f8e40a01366fa7e1d55b623f6471b47311771`
