### ISSUE TITLE
Bug: video embed larger than the viewport when embeds are enabled

### ISSUE THREAD

**Issue by wraithy** [dicedtomatoreal/typex#523]
### What happened?

![image](https://github.com/diced/zipline/assets/83000298/827ac46d-4977-4d78-bd27-c701434e9169)

Adding the following CSS fixes the issue (will probably need a class/id to avoid affecting other video elements)

```css
video {
    max-width: 100vw;
    max-height: 100vh;
}
```

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)
