### ISSUE TITLE
Bug: Page never loads behind traefik

### ISSUE THREAD

**Issue by sahara101** [dicedtomatoreal/typex#599]
### What happened?

Hello, 

in V3, with traefik labels, the login page never loads. Ib V4 it works as expected. 

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### Zipline Logs

```shell
2024-08-31 11:28:29,402 AM info  [server::response] GET /api/user -> 401
```

### Additional Info

```
labels:
     traefik.enable: true
     traefik.http.routers.zipline.entryPoints: https
     traefik.http.routers.zipline.rule: Host(`zipline.mydomain.org`)
     traefik.http.routers.zipline.middlewares: crowdsec@file, error-pages-middleware
     ```
