### ISSUE TITLE
Bug: Zipline losing connection to the database every few days

### ISSUE THREAD

**Issue by wraithy** [dicedtomatoreal/typex#778]
### What happened?

So I updated Zipline which did fix the S3 issue however I am now getting database issues after Zipline has been running for a day or 2.

### Version

Latest v4 commit (ghcr.io/diced/zipline:trunk)

### Zipline Logs

```shell
Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 7)
    at async Object.func (src/lib/tasks/run/deleteFiles.ts:7:25) {
  code: 'P2024',
  clientVersion: '6.4.1',
  meta: [Object]
}
 ⨯ unhandledRejection:  Error [PrismaClientKnownRequestError]: 
Invalid `prisma.file.findMany()` invocation:


Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 7)
    at async Object.func (src/lib/tasks/run/maxViews.ts:8:18) {
  code: 'P2024',
  clientVersion: '6.4.1',
  meta: [Object]
}
 ⨯ unhandledRejection:  Error [PrismaClientKnownRequestError]: 
Invalid `prisma.file.aggregate()` invocation:


Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 7)
    at async queryStats (src/lib/stats.ts:5:15)
    at async Object.func (src/lib/tasks/run/metrics.ts:6:18) {
  code: 'P2024',
  clientVersion: '6.4.1',
  meta: [Object]
}
 ⨯ unhandledRejection:  Error [PrismaClientKnownRequestError]: 
Invalid `prisma.file.findMany()` invocation:


Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 7)
    at async Object.func (src/lib/tasks/run/thumbnails.ts:13:28) {
  code: 'P2024',
  clientVersion: '6.4.1',
  meta: [Object]
}
 ⨯ unhandledRejection:  Error [PrismaClientKnownRequestError]: 
Invalid `prisma.invite.findMany()` invocation:


Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 7)
    at async Object.func (src/lib/tasks/run/clearInvites.ts:5:27) {
  code: 'P2024',
  clientVersion: '6.4.1',
  meta: [Object]
}
 ⨯ unhandledRejection:  Error [PrismaClientKnownRequestError]: 
Invalid `prisma.file.findMany()` invocation:


Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 7)
    at async Object.func (src/lib/tasks/run/deleteFiles.ts:7:25) {
  code: 'P2024',
  clientVersion: '6.4.1',
  meta: [Object]
}
 ⨯ unhandledRejection:  Error [PrismaClientKnownRequestError]: 
Invalid `prisma.file.findMany()` invocation:


Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 7)
    at async Object.func (src/lib/tasks/run/maxViews.ts:8:18) {
  code: 'P2024',
  clientVersion: '6.4.1',
  meta: [Object]
}
 ⨯ unhandledRejection:  Error [PrismaClientKnownRequestError]: 
Invalid `prisma.file.aggregate()` invocation:


Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 7)
    at async queryStats (src/lib/stats.ts:5:15)
    at async Object.func (src/lib/tasks/run/metrics.ts:6:18) {
  code: 'P2024',
  clientVersion: '6.4.1',
  meta: [Object]
}
 ⨯ unhandledRejection:  Error [PrismaClientKnownRequestError]: 
Invalid `prisma.file.findMany()` invocation:


Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 7)
    at async Object.func (src/lib/tasks/run/thumbnails.ts:13:28) {
  code: 'P2024',
  clientVersion: '6.4.1',
  meta: [Object]
}
 ⨯ unhandledRejection:  Error [PrismaClientKnownRequestError]: 
Invalid `prisma.invite.findMany()` invocation:


Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 7)
    at async Object.func (src/lib/tasks/run/clearInvites.ts:5:27) {
  code: 'P2024',
  clientVersion: '6.4.1',
  meta: [Object]
}
 ⨯ unhandledRejection:  Error [PrismaClientKnownRequestError]: 
Invalid `prisma.file.findMany()` invocation:


Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 7)
    at async Object.func (src/lib/tasks/run/deleteFiles.ts:7:25) {
  code: 'P2024',
  clientVersion: '6.4.1',
  meta: [Object]
}
 ⨯ unhandledRejection:  Error [PrismaClientKnownRequestError]: 
Invalid `prisma.file.findMany()` invocation:


Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 7)
    at async Object.func (src/lib/tasks/run/maxViews.ts:8:18) {
  code: 'P2024',
  clientVersion: '6.4.1',
  meta: [Object]
}
 ⨯ unhandledRejection:  Error [PrismaClientKnownRequestError]: 
Invalid `prisma.file.aggregate()` invocation:


Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 7)
    at async queryStats (src/lib/stats.ts:5:15)
    at async Object.func (src/lib/tasks/run/metrics.ts:6:18) {
  code: 'P2024',
  clientVersion: '6.4.1',
  meta: [Object]
}
 ⨯ unhandledRejection:  Error [PrismaClientKnownRequestError]: 
Invalid `prisma.file.findMany()` invocation:


Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 7)
    at async Object.func (src/lib/tasks/run/thumbnails.ts:13:28) {
  code: 'P2024',
  clientVersion: '6.4.1',
  meta: [Object]
}
 ⨯ unhandledRejection:  Error [PrismaClientKnownRequestError]: 
Invalid `prisma.invite.findMany()` invocation:


Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 7)
    at async Object.func (src/lib/tasks/run/clearInvites.ts:5:27) {
  code: 'P2024',
  clientVersion: '6.4.1',
  meta: [Object]
}
```

### Browser Logs

```shell

```

**Comment by diced** [comment]
looks this this is only happening to the scheduled tasks.. does the dashboard work fine and show everything correctly? you can try enabling the healthcheck and try going to `/api/healthcheck` yourself in the browser to see if it returns an okay response

**Comment by wraithy** [comment]
> looks this this is only happening to the scheduled tasks.. does the dashboard work fine and show everything correctly? you can try enabling the healthcheck and try going to `/api/healthcheck` yourself in the browser to see if it returns an okay response

No, it just shows a loading circle and nothing works until I restart the Zipline instance. I have a schedule set up currently to restart the container each day so I will have to wait before I can check the healthcheck endpoint but yeh nothing loads and you can't upload etc either. One thing that I did notice though is that the files are added to the database but the files don't actually get uploaded so they just show as broken files once I restart the instance.

**Comment by wraithy** [comment]
So I get this response when going to the `/api/healthcheck` endpoint

```
{
  "error": "there was an error during a healthcheck",
  "statusCode": 500
}
```

and then in the console it shows this
```
Invalid `prisma.$queryRaw()` invocation:


Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 7)
[2025-04-16T14:23:24 ERROR  api::healthcheck] there was an error during a healthcheck
[2025-04-16T14:23:24 ERROR  api::healthcheck] PrismaClientKnownRequestError:
```

**Comment by nikolanovoselec** [comment]
I have a similar problem. I didn't find anything in the logs about loosing connection to the database, but all my uploaded files disappear every few days and I simply receive "404 Page not found" for everything except shortened URLs.

Healthcheck returns {"pass":true}. This is my compose.yaml.

```
services:
  postgresql:
    image: postgres:16
    restart: unless-stopped
    container_name: tools_zipline_database
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER:-zipline}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD:?POSTGRESSQL_PASSWORD is required}
      POSTGRES_DB: ${POSTGRESQL_DB:-zipline}
    user: root
    volumes:
      - /mnt/configs/zipline/database:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'zipline']
      interval: 10s
      timeout: 5s
      retries: 5

  zipline:
    image: ghcr.io/diced/zipline
    container_name: tools_zipline_server
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRESQL_USER:-zipline}:${POSTGRESQL_PASSWORD}@postgresql:5432/${POSTGRESQL_DB:-zipline}
    user: root
    depends_on:
      - postgresql
    volumes:
      - /mnt/configs/zipline/uploads:/zipline/uploads
      - /mnt/configs/zipline/public:/zipline/public
      - /mnt/configs/zipline/themes:/zipline/themes
```

And here is my .env file.
```
POSTGRESQL_USER = zipline
POSTGRESQL_DB = zipline
POSTGRESQL_PASSWORD = [[ZIPLINE_DB_PASS]]
CORE_SECRET = [[ZIPLINE_CORE_SECRET]]
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/zipline?schema=public"
CORE_PORT=3000
CORE_HOSTNAME=0.0.0.0
DATASOURCE_TYPE="local"
DATASOURCE_LOCAL_DIRECTORY="/mnt/configs/zipline/uploads"
```
