### ISSUE TITLE
Bug: Unlinking OIDC provider seems to fail due to 404 URL

### ISSUE THREAD

**Issue by Spiritreader** [dicedtomatoreal/typex#783]
### What happened?

When attempting to unlink the OIDC provider, I'm getting a "404 not found" error.
It seems like the backend route that it attempts to call does not exist

![Image](https://github.com/user-attachments/assets/cf29116e-380a-4d25-878e-bff58145bf49)

![Image](https://github.com/user-attachments/assets/57572b8b-84de-4483-bf1c-061b92823280)

### Version

Latest v4 release (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox, Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

```shell

```

### Browser Logs

```shell
DELETE /api/auth/oauth HTTP/2
Host: zipline.example.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:138.0) Gecko/20100101 Firefox/138.0
Accept: */*
Accept-Language: en,en-US;q=0.5
Accept-Encoding: gzip, deflate, br, zstd
Referer: https://zipline.example.com/dashboard/settings
Content-Type: application/json
Content-Length: 19
Origin: https://zipline.example.com
DNT: 1
Connection: keep-alive
Cookie: user=XX
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Priority: u=0
TE: trailers

HTTP/2 404 
server: openresty
date: Sat, 12 Apr 2025 23:09:26 GMT
content-type: text/html; charset=utf-8
access-control-allow-origin: *
cache-control: private, no-cache, no-store, max-age=0, must-revalidate
x-powered-by: Next.js
etag: "r6e7cud9ey446"
vary: Accept-Encoding
content-encoding: gzip
X-Firefox-Spdy: h2


404

Page not found

Go Home
```

### Additional Info

compose file
```
  zipline:
    container_name: pt-zipline
    image: ghcr.io/diced/zipline:latest
    user: ${UID-99}:${GID-100}
    ports:
      - ${WEBUI_PORT}:3000
    restart: unless-stopped
    environment:
      - CORE_RETURN_HTTPS=true
      - CORE_SECRET=$CORE_SECRET
      - CORE_HOSTNAME=0.0.0.0
      - CORE_PORT=3000
      - DATABASE_URL=$DATABASE_URL
      - CORE_LOGGER=true
      - DATASOURCE_TYPE=local
      - DATASOURCE_LOCAL_DIRECTORY=./uploads
    networks:
      - local
    volumes:
      - /mnt/user/filesharing/zipline/uploads:/zipline/uploads
      - /mnt/user/filesharing/zipline/public:/zipline/public
````
