### ISSUE TITLE
Bug: Authentik/Oauth Sign-in "undefined Failed to fetch access token" HTTP 500

### ISSUE THREAD

**Issue by KatieTheDev** [dicedtomatoreal/typex#808]
### What happened?

With the latest v4 release, I get a HTTP 500 code with the message "undefined Failed to fetch access token" whenever I try to log in with Authentik version 2025.4.0, which is the latest version as of today. This message is returned after logging in with Authentik, in the stage where the oauth token is passed back to Zipline.  Below is a list of scopes granted to the Provider for Zipline in Authentik:

![Image](https://github.com/user-attachments/assets/5e68abde-efbd-4f96-b7c1-fb84dabdb5dd)

### Version

Latest v4 release (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Tested on Librewolf 135.0.1, a fork of Firefox with extra privacy and security hardening. Also tested with Fennec for F-Droid version 138.0.0 on my Google Pixel 9. 

### Zipline Logs

```shell
katiethedev@Docker:/etc/docker-compose/zipline$ sudo docker compose up
[+] Running 3/3
 ✔ Network zipline_default         Created                                                                         0.1s
 ✔ Container zipline-postgresql-1  Created                                                                         0.1s
 ✔ Container zipline-zipline-1     Created                                                                         0.1s
Attaching to postgresql-1, zipline-1
postgresql-1  |
postgresql-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgresql-1  |
postgresql-1  | 2025-05-13 03:49:09.570 UTC [1] LOG:  starting PostgreSQL 16.9 (Debian 16.9-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgresql-1  | 2025-05-13 03:49:09.572 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgresql-1  | 2025-05-13 03:49:09.572 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgresql-1  | 2025-05-13 03:49:09.577 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresql-1  | 2025-05-13 03:49:09.592 UTC [28] LOG:  database system was shut down at 2025-05-13 03:48:37 UTC
postgresql-1  | 2025-05-13 03:49:09.611 UTC [1] LOG:  database system is ready to accept connections
zipline-1     | [2025-05-13T03:49:10 INFO   db] connecting to database postgres://zipline:[DB PASSWORD]@postgresql:5432/zipline
zipline-1     | [2025-05-13T03:49:13 INFO   server] starting zipline mode="production" version="4.0.2" argv=[]
zipline-1     | [2025-05-13T03:49:13 DEBUG  migrations] running migrations...
zipline-1     | [2025-05-13T03:49:13 DEBUG  migrations] ensuring database exists...
zipline-1     | [2025-05-13T03:49:13 DEBUG  migrations] applying migrations...
zipline-1     | [2025-05-13T03:49:13 DEBUG  migrations] no migrations applied
zipline-1     | [2025-05-13T03:49:13 INFO   server] reading settings...
zipline-1     | [2025-05-13T03:49:13 DEBUG  config::validate] reloaded config
zipline-1     | [2025-05-13T03:49:21 INFO   server] server started hostname="0.0.0.0" port=3000
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks] starting tasks tasks=7
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks] running first run id="deletefiles"
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks] started interval task id="deletefiles" interval=1800000
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks] running first run id="maxviews"
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks] started interval task id="maxviews" interval=1800000
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks] running first run id="metrics"
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks] started interval task id="metrics" interval=1800000
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks] started worker id="thumbnail-0"
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks] started worker id="thumbnail-1"
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks] running first run id="thumbnails"
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks] started interval task id="thumbnails" interval=1800000
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks] running first run id="clearinvites"
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks] started interval task id="clearinvites" interval=1800000
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks::deletefiles] found 0 expired files files=[]
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks::maxviews] found 0 expired files files=[]
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks::clearinvites] found 0 expired invites files=[]
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks::maxviews] found 0 expired urls dests=[]
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks::clearinvites] found 0 max used invites files=[]
zipline-1     | [2025-05-13T03:49:21 DEBUG  tasks::metrics] created metric id="cmalz39660000s201d5if5fh0" metric={"files":1,"urls":1,"users":1,"storage":306952,"fileViews":5,"urlViews":4,"filesUsers":[{"username":"KatieTheDev","sum":1,"storage":306952,"views":5}],"urlsUsers":[{"username":"KatieTheDev","sum":1,"views":4}],"types":[{"type":"image/png","sum":1}]}
zipline-1     | [2025-05-13T03:49:22 DEBUG  tasks::thumbnail-1] started thumbnail worker
zipline-1     | [2025-05-13T03:49:22 DEBUG  tasks::thumbnail-0] started thumbnail worker
zipline-1     | [2025-05-13T03:49:42 DEBUG  api::auth::oauth::oidc] oidc oauth request body="client_id=[REDACTED]&client_secret=[REDACTED]&grant_type=authorization_code&code=[REDACTED]&redirect_uri=https%3A%2F%2F[ZIPLINE DOMAIN]%2Fapi%2Fauth%2Foauth%2Foidc"
zipline-1     | [2025-05-13T03:49:42 WARN   api::auth::oauth::oidc] invalid oauth request error="Failed to fetch access token"
```

### Browser Logs

```shell
Partitioned cookie or storage access was provided to “https://[ZIPLINE DOMAIN]/api/auth/oauth/oidc?code=[REDACTED]” because it is loaded in the third-party context and dynamic state partitioning is enabled.

A resource is blocked by OpaqueResponseBlocking, please check browser console for details.
```

### Additional Info

I have redacted secrets present in the logs with [REDACTED] when obvious and with a description such as [ZIPLINE DOMAIN] when it may be less obvious. The logs shown from zipline are when starting Zipline from a compose file:

```yml
services:
  postgresql:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER:-zipline}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD:?POSTGRESSQL_PASSWORD is required}
      POSTGRES_DB: ${POSTGRESQL_DB:-zipline}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'zipline']
      interval: 10s
      timeout: 5s
      retries: 5

  zipline:
    image: ghcr.io/diced/zipline:latest
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRESQL_USER:-zipline}:${POSTGRESQL_PASSWORD}@postgresql:5432/${POSTGRESQL_DB:-zipline}
      - DEBUG=zipline
    depends_on:
      - postgresql
    volumes:
      - '[UPLOADS LOCATION]:/zipline/uploads'
      - '[PUBLIC LOCATION]:/zipline/public'
      - '[THEME LOCATION]:/zipline/themes'
```

I use a `.env` to define environment variables. I have censored the locations of files for security reasons.

I also have placed Zipline behind NGINX, with the following config `zipline.conf`:

```
server {
    # Listen default port for http
    listen 80;

    # Server name for this config
    server_name [ZIPLINE DOMAIN] www.[ZIPLINE DOMAIN];

    # Force redirect to https
    rewrite ^ https://$server_name$request_uri? permanent;
}

server {
    # Listen https connections
    listen 443 ssl;
    http2 on;

    # Server name for this config
    server_name [ZIPLINE DOMAIN] www.[ZIPLINE DOMAIN];

    # Certs
    ssl_certificate /etc/letsencrypt/live/[ZIPLINE DOMAIN]/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/[ZIPLINE DOMAIN]/privkey.pem;
    add_header Strict-Transport-Security "max-age=63072000" always;

    # Your custom nginx params for the site
    # This case returns page with a plain text
    location / {
        proxy_pass http://[ZIPLINE HOST]:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

I have also redacted sections of the NGINX config such as domains and IP addresses. I will note that both the NGINX server and Zipline reside on the same network and same VLAN. This config is located on a VM running Ubuntu 24.04 LTS.
