### ISSUE TITLE
Bug: Zipline S3 fails saying self signed certificate on LetsEncrypt certificate

### ISSUE THREAD

**Issue by clbx** [dicedtomatoreal/typex#813]
### What happened?

Zipline is failing to start with the following error:
```
[zipline][2025-05-26T01:08:10 ERROR  datasource::s3] there was an error while testing access code="DEPTH_ZERO_SELF_SIGNED_CERT" $metadata={"attempts":1,"totalRetryDelay":0}
```

To my self hosted MinIO instance, but the certificate is not self signed, nor is it expired 

```
        - name: DATASOURCE_S3_ENDPOINT
          value: https://s3.<redacted>.org
```

```
 openssl s_client -showcerts -connect s3.<redacted>.org:443
Connecting to 192.168.3.201
CONNECTED(00000006)
depth=2 C=US, O=Internet Security Research Group, CN=ISRG Root X1
verify return:1
depth=1 C=US, O=Let's Encrypt, CN=R11
verify return:1
depth=0 CN=s3.<redacted>.org
verify return:1
---
Certificate chain
 0 s:CN=s3.<redacted>.org
   i:C=US, O=Let's Encrypt, CN=R11
   a:PKEY: RSA, 2048 (bit); sigalg: sha256WithRSAEncryption
   v:NotBefore: May 21 20:04:18 2025 GMT; NotAfter: Aug 19 20:04:17 2025 GMT



### Version

Latest v4 release (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Safari

### Zipline Logs

```shell
[zipline][2025-05-26T01:13:16 INFO   db] connecting to database 
[zipline][2025-05-26T01:13:17 INFO   server] starting zipline mode="production" version="4.1.0" argv=[]
[zipline][2025-05-26T01:13:17 DEBUG  migrations] running migrations...
[zipline][2025-05-26T01:13:17 DEBUG  migrations] ensuring database exists...
[zipline][2025-05-26T01:13:18 DEBUG  migrations] applying migrations...
[zipline][2025-05-26T01:13:18 DEBUG  migrations] no migrations applied
[zipline][2025-05-26T01:13:18 INFO   server] reading settings...
[zipline][2025-05-26T01:13:18 DEBUG  config::validate] reloaded config
[zipline][2025-05-26T01:13:18 ERROR  datasource::s3] there was an error while testing access code="DEPTH_ZERO_SELF_SIGNED_CERT" $metadata={"attempts":1,"totalRetryDelay":0}
[zipline][2025-05-26T01:13:18 ERROR  datasource::s3] zipline will now exit
```

### Browser Logs

```shell
n/a
```

**Comment by diced** [comment]
give e8380cc261c00e76c66a5810f2588a4e777c3eab a try

**Comment by clbx** [comment]
Getting this now:

```
[2025-05-27T02:23:54 ERROR  datasource::s3] there was an error while testing access $metadata={"attempts":1,"totalRetryDelay":0}
```

This was working about a week ago, I had the image tagged ``latest`` so I tried with ``4.0.2`` and its working. Looks like there may be a regression?  I'm going to stick with 4.0.2 for now, but I'm willing to assist with testing.

**Comment by diced** [comment]
The only thing that changed was the logic that checks if Zipline can access your buckets:
- checks if it can write (create) a new file
- then checks if it can read this file
- then finally checks if it can delete the file

i would check the logs of your s3 provider if possible + check permissions, but if that isn't possible I can add a small log that gives out more info

here is a diff for more about what changed: `https://github.com/diced/zipline/compare/v4.0.2...v4.1.0#diff-bf280137ca5fa796fb6210b3d11272cacda6e3e6f71616476f3ea1fdae16c6b7` (for some reason github wont let me paste the url for this normally so just open this in a new tab then click "Files changed" which should jump to the correct file)

**Comment by clbx** [comment]
Okay yeah I'm seeing that, doesn't look like a regression, it's just getting caught earlier. I didn't actually upload anything to the deployment I had "working" on 4.0.2, as soon as a try uploading anything on 4.0.2 I get a similar error

```
[2025-05-27T03:14:00 ERROR  datasource::s3] there was an error while putting object code="DEPTH_ZERO_SELF_SIGNED_CERT" $metadata={"attempts":1,"totalRetryDelay":0}
```

If its possible to add more debug output, that would be appreicated. I use this MinIO instance for a lot more than just this and haven't had any issues so I'm pretty confident its at least not the cert that its serving at my s3 endpoint. I double checked the access/secret keys and they are correct and can list, upload, and delete objects.

**Comment by diced** [comment]
did you try the `trunk-e8380cc` tag? you can also try setting the environment variable `NODE_TLS_REJECT_UNAUTHORIZED=0`

**Comment by clbx** [comment]
Yes I tried the tag and got what’s in this comment

https://github.com/diced/zipline/issues/813#issuecomment-2910929443

I’d like to avoid disabling tls verification

**Comment by diced** [comment]
> Yes I tried the tag and got what’s in this comment

I added more logging at this point, ghcr.io/diced/zipline:trunk-amd64

> I’d like to avoid disabling tls verification

I get this, and I'll most likely remove these changes i've added, but I don't really know what the issue is here and it's difficult to reproduce or test on my end, there could be a lot of different issues, like a few that went through my mind are:
- does node not trust isrg root x1? yes it does, looking through `tls.rootCertificates`
- maybe your openssl version is 1.x? probably not since 3.x has been out for a while
- i could try adding something into zipline that lets you define extra CAs to add but i'd rather not do this, same with ignoring unauthorized certs
- you could ask an llm, which says its an error you might have made when configuring ssl in minio, so maybe double check that

from what I see it looks fine and not really a zipline problem if node is unable to verify your ssl cert in that specific domain.

**Comment by clbx** [comment]
```
[Error: self-signed certificate] {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT',
  '$metadata': [Object]
}
```

Getting this on the trunk tag. The cert is valid, I can curl the s3 endpoint from the zipline pod and don't get any certificate errors

```
/zipline # curl https://s3.<redacted>.org
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><Region>us</Region><RequestId>1846F063940A4037</RequestId><HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId></Error>/zipline # 
```

The cert is issued from LetsEncrypt using Cert Manager

**Comment by clbx** [comment]
I added the flag for node to ignore unverified certs and I'm getting this now

```
(node:1) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
Error: Expected closing tag 'hr' (opened in line 5, col 1) instead of closing tag 'body'.:6:1
  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
    at <unknown> (Error: Expected closing tag 'hr' (opened in line 5, col 1) instead of closing tag 'body'.:6:1) {
  '$metadata': [Object]
}
[2025-06-08T02:49:11 ERROR  datasource::s3] there was an error while testing access $metadata={"attempts":1,"totalRetryDelay":0}
[2025-06-08T02:49:11 ERROR  datasource::s3] zipline will now exit
```

Here are my environment variables, am I doing something wrong?

```
        env:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: DEBUG
          value: "zipline"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: zipline-secret
              key: DATABASE_URL
        - name: DATASOURCE_TYPE
          value: s3
        - name: DATASOURCE_S3_BUCKET
          value: fileshare
        - name: DATASOURCE_S3_REGION
          value: us
        - name: DATASOURCE_S3_ENDPOINT
          value: https://s3.<redacted>.org
        - name: DATASOURCE_S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: zipline-secret
              key: DATASOURCE_S3_ACCESS_KEY_ID
        - name: DATASOURCE_S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: zipline-secret
              key: DATASOURCE_S3_SECRET_ACCESS_KEY
        - name: CORE_SECRET
          valueFrom:
            secretKeyRef:
              name: zipline-secret
              key: CORE_SECRET
```
